version: "3.3"
services:
  cascade_gui:
    container_name: cascade_gui
    build:
      context: .
      dockerfile: Dockerfile
    image: cascadegui:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 3000:80
    restart: unless-stopped
    networks:
      - environment_zai_network

networks:
    environment_zai_network:
        external: true
